# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: zpa-app-segment-task
# Description: Create/delete/update Application Segments

terraform {
  required_version = ">= 0.13.0, < 1.2.0"
  required_providers {
    zpa = {
      source  = "zscaler/zpa"
      version = "2.3.0"
    }
  }
  backend "consul" {
    address = "localhost:8500"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}

provider "zpa" {
  zpa_client_id     = var.zpa.zpa_client_id
  zpa_client_secret = var.zpa.zpa_client_secret
  zpa_customer_id   = var.zpa.zpa_customer_id
}

# Create/delete/update Application Segments
module "zpa-app-segment-task" {
  source   = "/Users/wguilherme/go/src/github.com/zscaler/terraform-zpa-application-segment-nia"
  services = var.services

}
