# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: zpa-app-segment-task
# Description: Create/delete/update Application Segments

zpa = {
  zpa_client_id     = "MjE2MTk2MjU3MzMxMjgyMDcwLTg0MTgyN2I5LTEwMDQtNDE0Mi1iYjQwLTVlOGE0NWEyMjc2MQ=="
  zpa_client_secret = "HBRM'}IQgum#Yd~VxDz*d]@X6]Zab)<N"
  zpa_customer_id   = "216196257331281920"
}
