# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: zpa-app-segment-task
# Description: Create/delete/update Application Segments

services = {
  api = {
    address         = "172.17.0.1"
    id              = "api"
    kind            = ""
    meta            = {}
    name            = "api"
    node            = "foobar"
    node_address    = "192.168.10.10"
    node_datacenter = "dc1"
    node_id         = "node_a"
    node_meta       = {}
    node_tagged_addresses = {
      lan = "192.168.10.10"
      wan = "10.0.10.10"
    }
    port   = 80
    status = "passing"
    tags   = []
  }
  web_1 = {
    address         = "172.17.0.3"
    id              = "web_1"
    kind            = ""
    meta            = {}
    name            = "web"
    node            = "foobar"
    node_address    = "192.168.10.10"
    node_datacenter = "dc1"
    node_id         = "node_a"
    node_meta = {
      somekey = "somevalue"
    }
    node_tagged_addresses = {
      lan = "192.168.10.10"
      wan = "10.0.10.10"
    }
    port   = 5000
    status = "passing"
    tags   = ["tacos"]
  }
  web_2 = {
    address         = "172.17.0.3"
    id              = "web_2"
    kind            = ""
    meta            = {}
    name            = "web"
    node            = "foobarbaz"
    node_address    = "192.168.10.11"
    node_datacenter = "dc1"
    node_id         = "node_b"
    node_meta       = {}
    node_tagged_addresses = {
      lan = "192.168.10.11"
      wan = "10.0.10.10"
    }
    port   = 5000
    status = "passing"
    tags   = ["burrito"]
  }
}

